#
session:
  key: ''
  secret: 'test'
  cookie:
    path: '/'
    httpOnly: true
    maxAge: null
  resave: true
  saveUninitialized: true
  proxy: null


  #elasticsearch
elasticsearch:
  indexName: intime